sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    otherSprite.destroy(effects.warmRadial, 500)
    music.baDing.play()
    info.changeScoreBy(1)
})
let bugs: Sprite = null
scene.setBackgroundImage(img`
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dccccccccccccccccccccccccccccccccccddfbbddccccccccccccccccccccccccccccccccccdddfbbddccccccccccccccccccccccccccccccccccdddfbbdcccccccccccccccccccccccccccccccccdd
    dccddddddddddddddddddccccccccccccccddfbbddccddddddddddddddddddccccccccccccccdddfbbddccddddddddddddddddddccccccccccccccdddfbbdccddddddddddddddddddcccccccccccccdd
    dccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbdccdbbbbbbbbbbbbbbbbdcc22cc22cc22cdd
    dccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbdccdbbbbbbbbbbbbbbbbdcc22cc22cc22cdd
    dccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbdccdbbbbbbbbbbbbbbbbdcc22cc22cc22cdd
    dccdbbbbbbbbbbbbbbbbdccccccccccccccddfbbddccdbbbbbbbbbbbbbbbbdccccccccccccccdddfbbddccdbbbbbbbbbbbbbbbbdccccccccccccccdddfbbdccdbbbbbbbbbbbbbbbbdcccccccccccccdd
    dccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbddccdbbbbbbbbbbbbbbbbdcc22cc22cc22ccdddfbbdccdbbbbbbbbbbbbbbbbdcc22cc22cc22cdd
    dccdbbbbb2bbbbbbbbbbdcc22cc22cc22ccddfbbddccdbbbbb2bbbbbbbbbbdcc22cc22cc22ccdddfbbddccdbbbbb2bbbbbbbbbbdcc22cc22cc22ccdddfbbdccdbbbbb2bbbbbbbbbbdcc22cc22cc22cdd
    dccdbbbbbb2ffbbbbbbbdcc22cc22cc22ccddfbbddccdbbbbbb2ffbbbbbbbdcc22cc22cc22ccdddfbbddccdbbbbbb2ffbbbbbbbdcc22cc22cc22ccdddfbbdccdbbbbbb2ffbbbbbbbdcc22cc22cc22cdd
    dccdbbbbbff2fffbbbbbdccccccccccccccddfbbddccdbbbbbff2fffbbbbbdccccccccccccccdddfbbddccdbbbbbff2fffbbbbbdccccccccccccccdddfbbdccdbbbbbff2fffbbbbbdcccccccccccccdd
    dccdbbbbfff2efffbbbbdccccccccccccccddfbbddccdbbbbfff2efffbbbbdccccccccccccccdddfbbddccdbbbbfff2efffbbbbdccccccccccccccdddfbbdccdbbbbfff2efffbbbbdcccccccccccccdd
    dccdbbbffffffffffbbbdccccccc1c1c1ccddfbbddccdbbbffffffffffbbbdccccccc1c1c1ccdddfbbddccdbbbffffffffffbbbdccccccc1c1c1ccdddfbbdccdbbbffffffffffbbbdccccccc1c1c1cdd
    dccdbbfffffffffffbbbdccccccc1c1c1ccddfbbddccdbbfffffffffffbbbdccccccc1c1c1ccdddfbbddccdbbfffffffffffbbbdccccccc1c1c1ccdddfbbdccdbbfffffffffffbbbdccccccc1c1c1cdd
    dccdbbffffffffffffbbdccccccc1c1c1ccddfbbddccdbbffffffffffffbbdccccccc1c1c1ccdddfbbddccdbbffffffffffffbbdccccccc1c1c1ccdddfbbdccdbbffffffffffffbbdccccccc1c1c1cdd
    dccddddddddddddddddddccccccccccccccddfbbddccddddddddddddddddddccccccccccccccdddfbbddccddddddddddddddddddccccccccccccccdddfbbdccddddddddddddddddddcccccccccccccdd
    dccccccccccccccccccccccccccccccccccddfbbddccccccccccccccccccccccccccccccccccdddfbbddccccccccccccccccccccccccccccccccccdddfbbdcccccccccccccccccccccccccccccccccdd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    ddddddcccccdddddddddddddcccccddddddddfbbdddddddcccccdddddddddddddcccccdddddddddfbbdddddddcccccdddddddddddddcccccdddddddddfbbddddddcccccdddddddddddddcccccddddddd
    ddddcccccccccdddddddddcccccccccddddddfbbdddddcccccccccdddddddddcccccccccdddddddfbbdddddcccccccccdddddddddcccccccccdddddddfbbddddcccccccccdddddddddcccccccccddddd
    dddcccccccccccdddddddcccccccccccdddddfbbddddcccccccccccdddddddcccccccccccddddddfbbddddcccccccccccdddddddcccccccccccddddddfbbdddcccccccccccdddddddcccccccccccdddd
    ddccccbcccdccccdddddccccbcccdccccddddfbbdddccccbcccdccccdddddccccbcccdccccdddddfbbdddccccbcccdccccdddddccccbcccdccccdddddfbbddccccbcccdccccdddddccccbcccdccccddd
    ddcccbdcccddcccdddddcccbdcccddcccddddfbbdddcccbdcccddcccdddddcccbdcccddcccdddddfbbdddcccbdcccddcccdddddcccbdcccddcccdddddfbbddcccbdcccddcccdddddcccbdcccddcccddd
    dcccbddcccdddcccdddcccbddcccdddcccdddfbbddcccbddcccdddcccdddcccbddcccdddcccddddfbbddcccbddcccdddcccdddcccbddcccdddcccddddfbbdcccbddcccdddcccdddcccbddcccdddcccdd
    dcccbddcccdddcccdddcccbddcccdddcccdddfbbddcccbddcccdddcccdddcccbddcccdddcccddddfbbddcccbddcccdddcccdddcccbddcccdddcccddddfbbdcccbddcccdddcccdddcccbddcccdddcccdd
    dcccbdccbccddcccdddcccbdccbccddcccdddfbbddcccbdccbccddcccdddcccbdccbccddcccddddfbbddcccbdccbccddcccdddcccbdccbccddcccddddfbbdcccbdccbccddcccdddcccbdccbccddcccdd
    dcccbdccbcccccccdddcccbdccbcccccccdddfbbddcccbdccbcccccccdddcccbdccbcccccccddddfbbddcccbdccbcccccccdddcccbdccbcccccccddddfbbdcccbdccbcccccccdddcccbdccbcccccccdd
    dcccccccccdcccccdddcccccccccdcccccdddfbbddcccccccccdcccccdddcccccccccdcccccddddfbbddcccccccccdcccccdddcccccccccdcccccddddfbbdcccccccccdcccccdddcccccccccdcccccdd
    ddcccccddddccccdddddcccccddddccccddddfbbdddcccccddddccccdddddcccccddddccccdddddfbbdddcccccddddccccdddddcccccddddccccdddddfbbddcccccddddccccdddddcccccddddccccddd
    ddccccbbbbbccccdddddccccbbbbbccccddddfbbdddccccbbbbbccccdddddccccbbbbbccccdddddfbbdddccccbbbbbccccdddddccccbbbbbccccdddddfbbddccccbbbbbccccdddddccccbbbbbccccddd
    dddcccccccccccdddddddcccccccccccdddddfbbddddcccccccccccdddddddcccccccccccddddddfbbddddcccccccccccdddddddcccccccccccddddddfbbdddcccccccccccdddddddcccccccccccdddd
    ddddcccccccccdddddddddcccccccccddddddfbbdddddcccccccccdddddddddcccccccccdddddddfbbdddddcccccccccdddddddddcccccccccdddddddfbbddddcccccccccdddddddddcccccccccddddd
    ddddddcccccccddddddddccccccccddddddddfbbdddddddcccccccddddddddccccccccdddddddddfbbdddddddcccccccddddddddccccccccdddddddddfbbddddddcccccccddddddddccccccccddddddd
    dddddddddddccccccccccccddddddddddddddfbbddddddddddddccccccccccccdddddddddddddddfbbddddddddddddccccccccccccdddddddddddddddfbbdddddddddddccccccccccccddddddddddddd
    dddddddddddddcccccccccdddddddddddddddfbbddddddddddddddcccccccccddddddddddddddddfbbddddddddddddddcccccccccddddddddddddddddfbbdddddddddddddcccccccccdddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dc11cc99cc11cc11cc99ccddcc11cc11cddddfbbddc11cc99cc11cc11cc11ccddcc11cc11cdddddfbbddc11cc11cc11cc11cc11ccddcc11cc99cdddddfbbdc11cc99cc11cc11cc11ccddcc11cc99cddd
    dc11cc99cc11cc11cc99ccddcc11cc11cddddfbbddc11cc99cc11cc11cc11ccddcc11cc11cdddddfbbddc11cc11cc11cc11cc11ccddcc11cc99cdddddfbbdc11cc99cc11cc11cc11ccddcc11cc99cddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dc11ccddcc11cc11cc11cc99cc11cc11cddddfbbddc11ccddcc99cc11cc11cc99cc11cc11cdddddfbbddc11ccddcc99cc11cc11cc99cc11cc11cdddddfbbdc11ccddcc11cc11cc11cc99cc11cc11cddd
    dc11ccddcc11cc11cc11cc99cc11cc11cddddfbbddc11ccddcc99cc11cc11cc99cc11cc11cdddddfbbddc11ccddcc99cc11cc11cc99cc11cc11cdddddfbbdc11ccddcc11cc11cc11cc99cc11cc11cddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dc11cc99cc11cc99cc11cc11ccddcc11cddddfbbddc11cc11cc11cc11cc11cc11ccddcc99cdddddfbbddc11cc99cc11cc11cc11cc11ccddcc11cdddddfbbdc11cc11cc11cc99cc11cc11ccddcc11cddd
    dc11cc99cc11cc99cc11cc11ccddcc11cddddfbbddc11cc11cc11cc11cc11cc11ccddcc99cdddddfbbddc11cc99cc11cc11cc11cc11ccddcc11cdddddfbbdc11cc11cc11cc99cc11cc11ccddcc11cddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dcccc66ccccc11ccccc66ccccc11cccccddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbddccccbbccccc11cccccbbccccc11cccccdddddfbbdccccbbccccc11cccccbbccccc11cccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dcccc11ccccc66ccccc11ccccc11cccccddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbddcccc11cccccbbccccc11ccccc11cccccdddddfbbdcccc11cccccbbccccc11ccccc11cccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dcccc11ccccc99ccccc11ccccc66cccccddddfbbddcccc11ccccc99ccccc11cccccbbcccccdddddfbbddcccc11ccccc11ccccc99cccccbbcccccdddddfbbdcccc11ccccc99ccccc11cccccbbcccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dccccccccccccccccccccccccccccccccddddfbbddccccccccccccccccccccccccccccccccdddddfbbddccccccccccccccccccccccccccccccccdddddfbbdccccccccccccccccccccccccccccccccddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    ddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbdddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdddddfbbddcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddfbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddd
    ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddfbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddd
    dddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddddddfbbdddddddddddddddddddddddddddddddddddd
    `)
let mySprite = sprites.create(img`
    . . . . f b b b b b f . . . 
    . . . f c 1 1 1 1 1 b f . . 
    . . f c 1 1 8 5 8 1 1 b f . 
    . f 5 1 1 1 5 8 5 1 1 5 f . 
    . f 8 5 5 5 5 5 5 5 5 8 f . 
    . f 8 8 8 8 8 8 8 8 8 8 f . 
    . . f c c f f 8 8 f f c c f 
    f c b b f d 1 f f 1 d c 3 f 
    c b b d f d f e e f d f b f 
    c b 8 d e f e d e e f 4 b . 
    . f 8 8 3 d d d d 3 8 c f . 
    f 8 8 8 1 4 b b b 1 8 8 f . 
    f 6 5 c 8 1 1 c 1 1 8 6 5 f 
    f e d f 8 c 8 8 8 8 8 b d f 
    . f f c 8 8 8 8 8 c f f f . 
    . . . . f f f f f f . . . . 
    . . . f f f . . f f f . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
mySprite.setStayInScreen(true)
info.setScore(0)
game.onUpdateInterval(500, function () {
    bugs = sprites.createProjectileFromSide(img`
        . . . . f . . . . . f . . . . 
        . . . . . f . . . f . . . . . 
        . . . . . f . . . f . . . . . 
        . . . . . . f f f . . . . . . 
        . . . . f b c b d b f . . . . 
        . . f f e 1 f c f 1 e f f . . 
        . f c 6 e e 1 1 1 e d 6 c f . 
        f e 6 4 4 4 e 6 d 4 4 4 6 e f 
        f e 4 5 d f 6 9 9 f d 5 4 4 f 
        f d 5 1 e f 6 6 9 f e 1 5 d f 
        . f e e f e f 6 c e f e e f . 
        . . . f d b b f f c d f . . . 
        . . . . c f . . . f c . . . . 
        `, randint(-50, 50), randint(-50, 50))
    bugs.setKind(SpriteKind.Food)
})
